src/FormStateApp.tsx, src/formState.test.tsx, src/formState.ts
Just a small quality-of-life improvement, I don't want to have to null check the `query.data` that I'm passing as an init value.
I _think_ this is a good idea. It's something I wanted in procurement-frontend's 1st form.
Also I moved to the "opts" approach to let the `initValue` be optional, per what @khalidwilliams ran into a few days ago.
=> feat: Refactor to opts, more flexible init BREAKING CHANGE

src/formState.test.tsx, src/formState.ts
This was my intent with the new API, but it wasn't covered by a test, so had a bug.
=> fix: Remove init from useMemo when it's not the input/map pair.

src/formState.test.tsx, src/formState.ts
Had a few places in internal-frontend that were passing `init.input: [...]` and expecting the array to be flatten into the `useMemo`'d list.
=> fix: Allow init.input to be an array.

src/formState.test.tsx, src/formState.ts
I'm getting ahead of things, but for having a single form drive both "create" and "update", in the new "auto save all the things" world, I'm anticipating wanting to change form behavior (i.e. required/optional labeling) based on "is this new or not".
I.e. if we're creating a trade partner, show the name field as `Name*`, but if we're viewing / editing a trade partner, just show the name field as `Name` (i.e. I'm anticipating that UX wants to kill "View vs Edit" as separate modes, but if you're always in Edit mode, it seems weird to literally always see the form Required/Optional hints).
So was thinking we could drive this behavior by either knowing "the form is in create mode or edit mode" or "the entity itself is new or not new".
And this 2nd "is the entity new" seemed like an easier …
=> feat: Add FieldState.isNewEntity.

src/formState.test.tsx, src/formState.ts
@DeanGilewicz noticed an existing bug in blueprint where:
* User hits cancel
* The query string `?edit=1` is unset
* The form state is put read only
* The navigation prompt says "are you sure?"
* User says yes, I'm sure leave me out of edit mode
* The form actions calls `formState.reset` to throw away WIP changes
* `formState.set` would either "do nothing" (for value fields) or "blow up" (for list fields)
Now we let the reset just happen, b/c we assume it's an "admin operation" that is known to be okay, and not literally, say, a form field mutating a read-only form state, which we still want to avoid/prevent.
=> fix: Allow reset while read only.

src/formState.test.tsx, src/formState.ts
This restores the behavior of "save a new contact" where if no address fields are filled in, then the address key isn't included in the payload.
=> fix: Don't include empty subobjects in changedValue.

src/formState.test.tsx, src/formState.ts
This should fix the issue Jonnathan noticed where having WIP values in a form will get lost if the Apollo cache rerenders.
We use the `field.dirty` flag to accept any new values (i.e. you probably want to see the latest values from the server), unless you have local changes, we'll keep your local changes.
=> feat: Keep work-in-progress form values after cache refreshes.

src/formState.test.tsx, src/formState.ts
Before the previous PR, this just worked b/c when new data came in we re-created the whole form state from scratch.
Now that we keep the old form state around, and call `.set` with the new data, the `.set` needs to not blow up when its read-only.
=> fix: Fix rerendering w/new data when read only.

src/formState.ts
This avoids warnings like:
```
console.error
Warning: Cannot update a component (`Observer`) while rendering a different component (`ToDoModal`). To locate the bad setState() call inside `ToDoModal`, follow the stack trace as described in https://fb.me/setstate-in-render
in ToDoModal
in StylesProvider
in div (created by $c5f9596976ab8bd94c5879001549a3e$var$OverlayContainerDOM)
```
Which are not fatal but still annoying.
=> fix: Update the form state within a useEffect.

src/formState.test.tsx, src/formState.ts
When a new mutation result came in, our 1st attempt at "don't loose user's WIP changes" (which was focused based) would ignore it.
We actually want to accept incoming values _if they match our current value_, so that fields are made clean.
Our 2nd attempt code (the `opts.refreshing`-aware code in `ValueField.set`) already knew about this, but the old code in `ObjectField.set` didn't so just remove the 1st attempt and use the 2nd attempt.
Fwiw it looks like we're basically not using "is focused" for anything at the moment, so could probably remove it?
=> fix: Fix focused fields ignoring incoming values.

src/formState.test.tsx, src/formState.ts
Previously b/c the identity of the list did not change, mobx caching
would kick-in and stop the notification.
We already had this `computed false` override for the core
formState.value, but weren't using it for child values.
=> fix: Make ListField.value observable.

src/useFormStates.ts
So that it can be used as a dependency for things like a `useMemo`-d `createColumns`.
=> fix: Make getObjectState stable.

src/useFormStates.test.tsx, src/useFormStates.ts
Open to not doing this, but I've thought a few times that `getFormState` would be closer to the `useFormState` (than `getObjectState`) that engineers typically to use to "use form state", so :shrug: , just throwing it out there.
=> feat: Rename getObjectState to getFormState.

src/formState.test.tsx, src/formState.ts, src/useFormStates.test.tsx, src/useFormStates.ts
I haven't been entirely happy about how the interaction in the past
of having `formState.readOnly = ...` set and then also adding in
per-field `formState.firstName.readOnly = ...` settings.
The current version was kind of ~last-write-win-ish, i.e. you could
set the base `formState` into `readOnly` but then override it with
a field-level set.
This wasn't terrible, but it always wasn't very declarative.
This PR changes to the approach that each field-level read-only-ness
is now just a combination of:
formState.readOnly || fieldState.readOnly
I.e. either form-level or field-level being true will lock the field.
This technically removes the ability, which the previous setup had,
of allowing a form-level readOnly=true but allowing a specific field
to opt-out and go back to readOnly=false. …
=> feat: Add useFormStates.readOnly, improve object/field interaction.

src/useFormState.test.tsx, src/useFormState.ts, src/utils.ts
This allows passing `query` directly to `init`:
```
const formState = useFormState({
config: formConfig,
init: {
query,
map: ({ toDos: [toDo] }) => ({
...toDo,
status: toDo.status.code,
type: toDo.type.code,
assigneeId: toDo.assignee?.internalUser?.id,
parentId: toDo.parent?.id,
attachments: toDo.attachments.map((a) => ({ ...a, op: "existing" })),
}),
ifUndefined: { parentId, attachments: [] },
},
autoSave: maybeAutoSave,
});
```
Which, I dunno, I think I actually like better than `init.input`, just in terms of saving the page from a little bit of "yeah yeah dig into the `query.data.asdfasdf` to pass to `init.input`".
=> feat: Add init.query overload to directly access loading.

src/FormStateApp.test.tsx, src/FormStateApp.tsx, src/fields/listField.ts, src/fields/objectField.ts, src/fields/valueField.ts, src/formState.test.tsx
Two reasons:
1. I'd always found the `fs.save()` to be somewhat unclear about
what it actually did.
2. If we eventually get fancy with handling both "auto save and
create save", having the `fs.save()` method name available would
be nice.
=> feat: Rename save/reset to commit/revertChanges.

src/AutoSaveStatus/index.ts
AutoSaveStatus had to be imported from `@homebound/form-state/dist/AutoSaveStatus/AutoSaveStatusProvider`. Oops.
=> fix(autosave): AutoSaveStatus as toplevel export

src/fields/valueField.ts, src/useFormState.test.tsx, src/useFormState.ts
We had a weird issue in Blueprint that has:
1. User is on task 1, `tradePartnerId = 123`
2. User moves to task 2, which sets `tradePartnerId = undefined`
* Because there was no `key=` in the sidebar component hierarchy, react treated this "move to the next row" as "just another re-render", so `useFormState` didn't realize this was essentially "a brand new/separate task" and instead treated the incoming `task` fragment as "a new version of the already-being-editted task"
3. When we set values like "TP 123" to `undefined`, we really store them as `null` so the backend knows to do a delete/unset of the field (so `tradePartnerId` was now stored internally as `null`)
4. We had a bug where `.value` would correctly turn `null` back into `undefined` on reads, but `.originalValue` (Which was also …
=> fix: Fix cache refreshes being mistaken as edits.

src/FormStateApp.tsx, src/config.ts, src/fields/listField.ts, src/fields/objectField.ts, src/fields/valueField.ts, src/formState.test.tsx, src/rules.ts, src/useFormState.test.tsx, src/useFormStates.test.tsx
Instead users can use addRules/other ways to do setup cross-field validation rules, instead of from within the rule itself.
=> feat: Simplify FieldState by removing rule object param.

package-lock.json, src/config.ts, src/fields/listField.ts, src/fields/objectField.ts, src/formState.test.tsx
Gives the option to turn off the strict order check for dirty instance.
=> feat: Change in order of rows in ListState mark it as dirty

src/fields/valueField.ts, src/formState.test.tsx, src/index.ts, src/proxies.ts
To handle easily doing feet/inches conversion for program data, i.e. something like:
```tsx
<BoundNumberField field={pd.widthInInches.adapt(inchesToFeet)} />
const inchesToFeet: ValueAdapter<number, number> = {
toValue: ...times 12...,
fromValue: ...divide by 12...,
};
```
=> feat: Add field state adapter

README.md, src/FormStateApp.tsx, src/config.ts, src/configBuilders.ts, src/fields/listField.ts, src/fields/objectField.ts, src/fields/valueField.ts, src/formState.test.tsx, src/index.ts, src/mobx-behavior.test.ts, src/stackoverlfow.ts, src/utils.ts
Instead of:
```ts
const formConfig: ObjectConfig<AuthorInput> = {
firstName: { type: "value", rules: [required] },
lastName: { type: "value", rules: [required], readOnly: true },
books: {
type: "list",
config: {
title: { type: "value", rules: [required] },
},
},
};
```
We can do:
```ts
const formConfig = f.config<AuthorInput>({
firstName: f.value().req(),
lastName: f.value().readOnly(),
books: f.list({
title: f.value().req(),
}),
});
```
=> feat: Add Zod-style config api

src/formState.test.tsx, src/useFormState.test.tsx, src/utils.ts
Got missed in the last refactoring of `originalValue` handling (which is used for dirty checking) that mobx computeds don't show up in `Object.keys`. :shrug:
=> fix: Fix computeds always being dirty.

src/fields/listField.ts, src/fields/objectField.ts, src/fields/valueField.ts, src/useFormState.test.tsx
With a check to make sure it's not us ourselves doing the mutation.
=> fix: Trigger auto-saves when observables are mutated directly.

src/config.ts, src/configBuilders.test.ts, src/configBuilders.ts, src/fields/listField.ts, src/fields/objectField.ts, src/fields/valueField.ts, src/formState.test.tsx, src/formStateDomain.ts
I.e. something like:
```ts
const authorForm = f.config({
id: f.value(),
publisher: f.reference(),
});
// if author.publisher had been { id: 1, name: ... }
authorForm.publisher.set(undefined);
const publisherId = author.changedValue.publisher?.id;
// this will be null is removed, for putting into a mutation
await saveAuthor({ ..., publisherId });
```
The idea is to help avoid tracking both "a id+name tuple for lazy SelectFields" and "a regular id field for changedValue to put on the wire" like I'm doing in the S&S/CE code atm:
```
updateProposedBidItem(bidItem: DisplayNamedFragment | undefined) {
this.proposedBidItem = bidItem;
this.proposedBidItemId = bidItem?.id ?? null;
}
```
Solely b/c (without this PR) it's easier to get `proposedBidItemId` into the mutation if it's a standalone key, …
=> feat: Teach changedValue to handle references

src/FormStateApp.tsx, src/useFormState.test.tsx, src/useFormState.ts, src/useFormStates.ts, src/utils.ts
We've had several auto-saving form-states not realize they should use init.input + map to get the latest data from the mutation response automatically included in the form.
In general, having `init: T` is a legacy/rare use case, so let's try removing it.
Callers that were doing `init: data` can now do `init { input: data }` although technically the `init.input` will pull in changes to `data` as its identity changes, while `init: data` would not.
If we roll this out and find a lot of places that need that `init: data` behavior, we could add something like:
```
init: {
input: data,
initOnlyOnce: true,
}
```
Or something like that, to be more explicit that they're requesting to not re-read the `input: data` value on each re-render.
=> feat: Require init.input or init.query.

src/useFormState.ts, src/useFormStates.ts
It can be really frustrating to wonder "wtf is this not working", and previously the fix was to "know where to go in the form-state source to set the break point an examine the form". :-|
=> feat: console.debug when auto saves are skipped.

package.json, src/fields/deepEquals.ts, src/formState.test.tsx, src/utils.ts, yarn.lock
Replaces fast-deep-equal with a copy/pasted/inlined version of a cycle-aware deepEquals.
=> fix: Fix max stack errors on cycles.

src/useFormState.test.tsx, src/useFormState.ts
A previous refactoring removed the ability to do `init: pojo` in
the API, and instead consolidated usage on `init: { input: pojo }`.
This was good, but a surprising artifact of `init: pojo` was that it did not re-init as the identity of pojo changes (vs. the `init.input = pojo` whcih *does* re-init as the identity changes).
This dictomoy between "one re-inits and one does not" was fairly aribtrary and was a big reason behind removing the "two ways of doing things".
That said, in rolling out the change to internal-frontend, a number of callers were enjoying the implicit useMemo-ification of their `init: pojo`, and so this PR adds an `init.onlyOnce` flag that basically restores the "don't watch the init.input identity" behavior.
=> feat: Add init.onlyOnce.

README.md, src/fields/valueField.ts, src/formState.test.tsx
Include some docs on commitChanges.
=> fix: The server acking an unset should clean the dirty flag.
